import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    {
      type: 'category',
      label: 'Overview',
      link: {
        type: 'generated-index',
        title: 'Project Overview',
        description: 'Renault Club Bulgaria — architecture, tech stack, and domain model',
        slug: '/overview',
      },
      items: [
        { type: 'autogenerated', dirName: 'overview' },
      ],
    },
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Developer Guides',
        description: 'Step-by-step guides for setting up and working with the RCB platform',
        slug: '/guides',
      },
      items: [
        { type: 'autogenerated', dirName: 'guides' },
      ],
    },
  ],

  adrSidebar: [
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'doc',
        id: 'adr/index',
      },
      items: [
        'adr/adr-001-postgresql-database-design',
        'adr/adr-005-iam-domain-boundary',
        'adr/adr-006-bulgarian-vehicle-apis',
        'adr/adr-007-payment-gateway',
        'adr/adr-template',
      ],
    },
  ],

  onboardingSidebar: [
    {
      type: 'category',
      label: 'Onboarding',
      link: {
        type: 'doc',
        id: 'onboarding/onboarding-index',
      },
      items: [
        {
          type: 'category',
          label: 'Authentication',
          link: { type: 'doc', id: 'onboarding/authentication/authentication-index' },
          items: ['onboarding/authentication/login-logout'],
        },
        {
          type: 'category',
          label: 'User Profile',
          link: { type: 'doc', id: 'onboarding/user-profile/user-profile-index' },
          items: [
            'onboarding/user-profile/profile-management',
            'onboarding/user-profile/membership-card',
            'onboarding/user-profile/push-notifications',
            'onboarding/user-profile/contact-form',
          ],
        },
        {
          type: 'category',
          label: 'Content & Discovery',
          link: { type: 'doc', id: 'onboarding/content/content-index' },
          items: [
            'onboarding/content/news',
            'onboarding/content/gallery',
            'onboarding/content/campaigns',
            'onboarding/content/partners',
          ],
        },
        {
          type: 'category',
          label: 'Events',
          link: { type: 'doc', id: 'onboarding/events/events-index' },
          items: [
            'onboarding/events/browsing-events',
            'onboarding/events/applying-to-events',
            'onboarding/events/event-checkin',
            'onboarding/events/event-results',
            'onboarding/events/peer-badge-nominations',
          ],
        },
        {
          type: 'category',
          label: 'Community',
          link: { type: 'doc', id: 'onboarding/community/community-index' },
          items: [
            'onboarding/community/chat',
            'onboarding/community/polls',
          ],
        },
        {
          type: 'category',
          label: 'Garage',
          link: { type: 'doc', id: 'onboarding/garage/garage-index' },
          items: [
            'onboarding/garage/car-management',
            'onboarding/garage/maintenance-alerts',
            'onboarding/garage/vehicle-checks',
            'onboarding/garage/car-ratings',
          ],
        },
        {
          type: 'category',
          label: 'Rewards & Gamification',
          link: { type: 'doc', id: 'onboarding/rewards-gamification/rewards-index' },
          items: [
            'onboarding/rewards-gamification/points-and-currency',
            'onboarding/rewards-gamification/ranks-and-levels',
            'onboarding/rewards-gamification/achievement-badges',
            'onboarding/rewards-gamification/peer-badges',
            'onboarding/rewards-gamification/leaderboards',
          ],
        },
        {
          type: 'category',
          label: 'Admin Guide',
          link: { type: 'doc', id: 'onboarding/admin/admin-index' },
          items: [
            'onboarding/admin/user-management',
            'onboarding/admin/member-lifecycle',
            'onboarding/admin/event-management',
            'onboarding/admin/event-checkin-admin',
            'onboarding/admin/news-management',
            'onboarding/admin/gallery-management',
            'onboarding/admin/campaign-management',
            'onboarding/admin/partners-management',
            'onboarding/admin/chat-moderation',
            'onboarding/admin/polls-management',
            'onboarding/admin/membership-cards',
            'onboarding/admin/reward-config',
            'onboarding/admin/feature-flags',
            'onboarding/admin/dashboard-metrics',
            'onboarding/admin/job-execution-logs',
          ],
        },
      ],
    },
  ],

  deploymentSidebar: [
    {
      type: 'category',
      label: 'Deployment & Operations',
      link: {
        type: 'doc',
        id: 'deployment/index',
      },
      items: [
        'deployment/architecture-overview',
        'deployment/vps-bootstrap',
        'deployment/environment-config',
        'deployment/github-actions-cicd',
        'deployment/deploy-rollback',
        'deployment/alertmanager-setup',
        'deployment/slack-notifications',
      ],
    },
  ],

  securitySidebar: [
    {
      type: 'category',
      label: 'Security & QA',
      link: {
        type: 'doc',
        id: 'security/index',
      },
      items: [
        'security/security-headers',
        'security/owasp-dependency-check',
        'security/load-testing',
        'security/zap-scan',
        'security/e2e-testing',
        'security/migration-cutover',
        'security/weekly-security-scan',
      ],
    },
  ],
};

export default sidebars;
