import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    {
      type: 'category',
      label: 'Overview',
      link: {
        type: 'generated-index',
        title: 'Project Overview',
        description: 'Renault Club Bulgaria — architecture, tech stack, and domain model',
        slug: '/overview',
      },
      items: [
        { type: 'autogenerated', dirName: 'overview' },
      ],
    },
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Developer Guides',
        description: 'Step-by-step guides for setting up and working with the RCB platform',
        slug: '/guides',
      },
      items: [
        { type: 'autogenerated', dirName: 'guides' },
      ],
    },
  ],

  adrSidebar: [
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'doc',
        id: 'adr/index',
      },
      items: [
        'adr/adr-001-postgresql-database-design',
        'adr/adr-005-iam-domain-boundary',
        'adr/adr-006-bulgarian-vehicle-apis',
        'adr/adr-007-payment-gateway',
      ],
    },
  ],

  deploymentSidebar: [
    {
      type: 'category',
      label: 'Deployment & Operations',
      link: {
        type: 'doc',
        id: 'deployment/index',
      },
      items: [
        'deployment/architecture-overview',
        'deployment/vps-bootstrap',
        'deployment/environment-config',
        'deployment/github-actions-cicd',
        'deployment/deploy-rollback',
        'deployment/alertmanager-setup',
        'deployment/slack-notifications',
      ],
    },
  ],
};

export default sidebars;
